[2020-01-07 16:11:05,617] [log.py|__console] [line:39] INFO    :当前执行测试用例ID->test_login001.1;测试点->手机号和密码为空
[2020-01-07 16:11:11,385] [log.py|__console] [line:39] INFO    :检查点->手机号不能为空
[2020-01-07 16:11:11,411] [log.py|__console] [line:39] INFO    :登录异常，返回实际结果是->:手机号不能为空
