[2020-01-07 16:11:29,237] [log.py|__console] [line:39] INFO    :当前执行测试用例ID->test_login001.2;测试点->手机号为空
[2020-01-07 16:11:34,451] [log.py|__console] [line:39] INFO    :检查点->手机号不能为空
[2020-01-07 16:11:34,487] [log.py|__console] [line:39] INFO    :登录异常，返回实际结果是->:手机号不能为空
