[2020-01-06 14:59:29,676] [log.py|__console] [line:41] DEBUG   :123456786
